defmodule Tunez.Repo.Migrations.RenameArtistCreateTimestampAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:artists), :created_at, to: :inserted_at
  end

  def down do
    rename table(:artists), :inserted_at, to: :created_at
  end
end
